//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoL_Info.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoL_Info.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All games.
        /// </summary>
        public static string AllGames {
            get {
                return ResourceManager.GetString("AllGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Matches.
        /// </summary>
        public static string AllMatches {
            get {
                return ResourceManager.GetString("AllMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key:.
        /// </summary>
        public static string ApiKeyField {
            get {
                return ResourceManager.GetString("ApiKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Farm: .
        /// </summary>
        public static string AverageFarm {
            get {
                return ResourceManager.GetString("AverageFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average KDA: .
        /// </summary>
        public static string AverageKDA {
            get {
                return ResourceManager.GetString("AverageKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Value.
        /// </summary>
        public static string AverageVal {
            get {
                return ResourceManager.GetString("AverageVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string BrRegion {
            get {
                return ResourceManager.GetString("BrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string BtnAccept {
            get {
                return ResourceManager.GetString("BtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept changes.
        /// </summary>
        public static string BtnAcceptSettingsTip {
            get {
                return ResourceManager.GetString("BtnAcceptSettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected team info.
        /// </summary>
        public static string BtnAcceptTip {
            get {
                return ResourceManager.GetString("BtnAcceptTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BtnNo {
            get {
                return ResourceManager.GetString("BtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm chart.
        /// </summary>
        public static string ChartFarm {
            get {
                return ResourceManager.GetString("ChartFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show farm chart.
        /// </summary>
        public static string ChartFarmTip {
            get {
                return ResourceManager.GetString("ChartFarmTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDA chart.
        /// </summary>
        public static string ChartKDA {
            get {
                return ResourceManager.GetString("ChartKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show KDA chart.
        /// </summary>
        public static string ChartKDATip {
            get {
                return ResourceManager.GetString("ChartKDATip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics by charts.
        /// </summary>
        public static string ChartsTip {
            get {
                return ResourceManager.GetString("ChartsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click right button.
        /// </summary>
        public static string ChartTip {
            get {
                return ResourceManager.GetString("ChartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current KDA: .
        /// </summary>
        public static string CurrentKDA {
            get {
                return ResourceManager.GetString("CurrentKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading has started!.
        /// </summary>
        public static string DownloadingMessage {
            get {
                return ResourceManager.GetString("DownloadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download additional player`s data from server.
        /// </summary>
        public static string DownloadingTip {
            get {
                return ResourceManager.GetString("DownloadingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Eng {
            get {
                return ResourceManager.GetString("Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU Nordic &amp; East.
        /// </summary>
        public static string EuneRegion {
            get {
                return ResourceManager.GetString("EuneRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU West.
        /// </summary>
        public static string EuwRegion {
            get {
                return ResourceManager.GetString("EuwRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minions per match.
        /// </summary>
        public static string FarmPerMatch {
            get {
                return ResourceManager.GetString("FarmPerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minions per minute.
        /// </summary>
        public static string FarmPerMinute {
            get {
                return ResourceManager.GetString("FarmPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Influence: .
        /// </summary>
        public static string Influence {
            get {
                return ResourceManager.GetString("Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click right button to change current KDA.
        /// </summary>
        public static string InfluenceRightButtonClickTip {
            get {
                return ResourceManager.GetString("InfluenceRightButtonClickTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percent of matches won by your forces (KDA &gt;= .
        /// </summary>
        public static string InfluenceTip {
            get {
                return ResourceManager.GetString("InfluenceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        public static string Item1 {
            get {
                return ResourceManager.GetString("Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        public static string Item2 {
            get {
                return ResourceManager.GetString("Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 3.
        /// </summary>
        public static string Item3 {
            get {
                return ResourceManager.GetString("Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 4.
        /// </summary>
        public static string Item4 {
            get {
                return ResourceManager.GetString("Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 5.
        /// </summary>
        public static string Item5 {
            get {
                return ResourceManager.GetString("Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 6.
        /// </summary>
        public static string Item6 {
            get {
                return ResourceManager.GetString("Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string JpRegion {
            get {
                return ResourceManager.GetString("JpRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kills and assists per deaths.
        /// </summary>
        public static string KDA {
            get {
                return ResourceManager.GetString("KDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        public static string KrRegion {
            get {
                return ResourceManager.GetString("KrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageField {
            get {
                return ResourceManager.GetString("LanguageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin America North.
        /// </summary>
        public static string LanRegion {
            get {
                return ResourceManager.GetString("LanRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin America South.
        /// </summary>
        public static string LasRegion {
            get {
                return ResourceManager.GetString("LasRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load personal data.
        /// </summary>
        public static string LoadBtnTip {
            get {
                return ResourceManager.GetString("LoadBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player`s data was loaded successfully!.
        /// </summary>
        public static string LoadedMessage {
            get {
                return ResourceManager.GetString("LoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo2 {
            get {
                object obj = ResourceManager.GetObject("Logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with server. Try again later..
        /// </summary>
        public static string LogProblemMessage {
            get {
                return ResourceManager.GetString("LogProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loser.
        /// </summary>
        public static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of matches:.
        /// </summary>
        public static string MatchesCount {
            get {
                return ResourceManager.GetString("MatchesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don`t have enough matches!.
        /// </summary>
        public static string MatchesFailedMessage {
            get {
                return ResourceManager.GetString("MatchesFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu.
        /// </summary>
        public static string MenuBtnTip {
            get {
                return ResourceManager.GetString("MenuBtnTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should log in!.
        /// </summary>
        public static string MenuFailedMessage {
            get {
                return ResourceManager.GetString("MenuFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minions.
        /// </summary>
        public static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your player name and press &apos;Log In&apos;.
        /// </summary>
        public static string NameFailedMessage {
            get {
                return ResourceManager.GetString("NameFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string NaRegion {
            get {
                return ResourceManager.GetString("NaRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceania.
        /// </summary>
        public static string OceRegion {
            get {
                return ResourceManager.GetString("OceRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture1 {
            get {
                object obj = ResourceManager.GetObject("Picture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture10 {
            get {
                object obj = ResourceManager.GetObject("Picture10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture11 {
            get {
                object obj = ResourceManager.GetObject("Picture11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture12 {
            get {
                object obj = ResourceManager.GetObject("Picture12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture2 {
            get {
                object obj = ResourceManager.GetObject("Picture2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture3 {
            get {
                object obj = ResourceManager.GetObject("Picture3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture4 {
            get {
                object obj = ResourceManager.GetObject("Picture4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture5 {
            get {
                object obj = ResourceManager.GetObject("Picture5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture6 {
            get {
                object obj = ResourceManager.GetObject("Picture6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture7 {
            get {
                object obj = ResourceManager.GetObject("Picture7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture8 {
            get {
                object obj = ResourceManager.GetObject("Picture8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture9 {
            get {
                object obj = ResourceManager.GetObject("Picture9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process is running now!.
        /// </summary>
        public static string ProcessDontOverMessage {
            get {
                return ResourceManager.GetString("ProcessDontOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked Matches.
        /// </summary>
        public static string RankedMatches {
            get {
                return ResourceManager.GetString("RankedMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string RegionField {
            get {
                return ResourceManager.GetString("RegionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don`t have required matches!.
        /// </summary>
        public static string RequiredMatches {
            get {
                return ResourceManager.GetString("RequiredMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        public static string RlAssassin {
            get {
                return ResourceManager.GetString("RlAssassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        public static string RlFighter {
            get {
                return ResourceManager.GetString("RlFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        public static string RlMage {
            get {
                return ResourceManager.GetString("RlMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman.
        /// </summary>
        public static string RlMarksman {
            get {
                return ResourceManager.GetString("RlMarksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string RlSupport {
            get {
                return ResourceManager.GetString("RlSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string RlTank {
            get {
                return ResourceManager.GetString("RlTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string RuRegion {
            get {
                return ResourceManager.GetString("RuRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Rus {
            get {
                return ResourceManager.GetString("Rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts were loaded.
        /// </summary>
        public static string SbCharts {
            get {
                return ResourceManager.GetString("SbCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches are downloading. Please wait....
        /// </summary>
        public static string SbDownload {
            get {
                return ResourceManager.GetString("SbDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu was opened.
        /// </summary>
        public static string SbMenu {
            get {
                return ResourceManager.GetString("SbMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team`s data was loaded.
        /// </summary>
        public static string SbPlayerToTeam {
            get {
                return ResourceManager.GetString("SbPlayerToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string SbReady {
            get {
                return ResourceManager.GetString("SbReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic was loaded.
        /// </summary>
        public static string SbStats {
            get {
                return ResourceManager.GetString("SbStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player`s data was loaded.
        /// </summary>
        public static string SbTeamToPlayer {
            get {
                return ResourceManager.GetString("SbTeamToPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check selected players!.
        /// </summary>
        public static string SelectedPlayersFailedMessage {
            get {
                return ResourceManager.GetString("SelectedPlayersFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsField {
            get {
                return ResourceManager.GetString("SettingsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Matches.
        /// </summary>
        public static string SimpleMatches {
            get {
                return ResourceManager.GetString("SimpleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show main information about player or team.
        /// </summary>
        public static string StatisticsTip {
            get {
                return ResourceManager.GetString("StatisticsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your player name.
        /// </summary>
        public static string SummonerLogTip {
            get {
                return ResourceManager.GetString("SummonerLogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TbDate {
            get {
                return ResourceManager.GetString("TbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm (minions per match).
        /// </summary>
        public static string TbFarm {
            get {
                return ResourceManager.GetString("TbFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero.
        /// </summary>
        public static string TbHero {
            get {
                return ResourceManager.GetString("TbHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDA (kills and assists per deaths).
        /// </summary>
        public static string TbKDA {
            get {
                return ResourceManager.GetString("TbKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        public static string TbLevel {
            get {
                return ResourceManager.GetString("TbLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string TbPosition {
            get {
                return ResourceManager.GetString("TbPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string TbSummoner {
            get {
                return ResourceManager.GetString("TbSummoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Mode.
        /// </summary>
        public static string TeamModeTitle {
            get {
                return ResourceManager.GetString("TeamModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select team members and show team info.
        /// </summary>
        public static string TeamTip {
            get {
                return ResourceManager.GetString("TeamTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string TextFarm {
            get {
                return ResourceManager.GetString("TextFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDA.
        /// </summary>
        public static string TextKDA {
            get {
                return ResourceManager.GetString("TextKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Day: .
        /// </summary>
        public static string TopDay {
            get {
                return ResourceManager.GetString("TopDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Role: .
        /// </summary>
        public static string TopRole {
            get {
                return ResourceManager.GetString("TopRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Line.
        /// </summary>
        public static string TrendLine {
            get {
                return ResourceManager.GetString("TrendLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string TrRegion {
            get {
                return ResourceManager.GetString("TrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update the list of matches?.
        /// </summary>
        public static string TryLoadNewDataMessage {
            get {
                return ResourceManager.GetString("TryLoadNewDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukranian.
        /// </summary>
        public static string Ukr {
            get {
                return ResourceManager.GetString("Ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Rate: .
        /// </summary>
        public static string WinRate {
            get {
                return ResourceManager.GetString("WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
    }
}
